steps:
  - name: 'maven:3.9.4-eclipse-temurin-17'
    entrypoint: 'mvn'
    args: ['clean', 'package']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - functions
      - deploy
      - FUNCTION_NAME
      - --region=europe-west1
      - --source=.
      - --trigger-http
      - --runtime=java17
      - --entry-point=gcfv2.GmSFTPParser
      - --allow-unauthenticated
      - --set-secrets
      - nevroAuthURL=projects/241881754384/secrets/nevro_AUTH_URL/versions/1
      - nevroClientID=projects/241881754384/secrets/nevro_CLIENT_ID/versions/1
      - nevroClientSecret=projects/241881754384/secrets/nevro_CLIENT_SECRET/versions/1
      - nevroJUploadURL=projects/241881754384/secrets/nevro_JSON_UPLOAD_URL/versions/1
      - nevroSFTPPass=projects/241881754384/secrets/nevro_SFTP_pass/versions/1
      - nevroSFTPHost=projects/241881754384/secrets/nevroSFTPHost/versions/1
      - nevroSFTPTestPath=projects/241881754384/secrets/nevroSFTPTESTFilePath/versions/1
      - nevroSFTPUser=projects/241881754384/secrets/nevroSFTPUser/versions/1
